#!/usr/bin/env python3
"""Static regression for QPV source KPI admin workflow."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PAGE = ROOT / "website" / "source-kpi-admin.html"
html = PAGE.read_text(encoding="utf-8")

required = [
    "qpvOrderLedger",
    "qpvPaymentProofLedger",
    "qpvConversionLedger",
    "qpvFollowUpLedger",
    "qpvRecoveryReminderLedger",
    "qpvRecoveryConversionHandoffLedger",
    "sourceFilter",
    "function sourceStats",
    "function allSources",
    "function sourceOf",
    "./offer.html?source=source_kpi_admin",
    "./checkout.html?source=source_kpi_admin",
    "./payment-ledger.html?source=source_kpi_admin",
    "./paid-confirmation.html",
    "./paid-confirmation.html?source=source_kpi_admin_recovery_handoff",
    "Manual paid gate",
    "openPaidGate",
    "paidGateHref",
    "./order-admin.html",
    "Order admin",
    "./revenue-command-center.html",
    "Revenue command center",
    "./payment-recovery-queue.html?source=source_kpi_admin_recovery",
    "Payment recovery dashboard",
    "Payment recovery queue",
    "openRecoveryQueue",
    "openTopRecovery",
    "copyTopRecoveryMessage",
    "function topRecoveryMessage",
    "latestTopRecoveryMessage",
    "topRecoveryMessageRevenueEur:0",
    "Copy top recovery message",
    "No top unpaid recovery message to copy.",
    "Top unpaid recovery message copied. Revenue remains 0 EUR until verified paid.",
    "copied top recovery message is not revenue",
    "markTopRecoveryReminder",
    "function markTopRecoveryReminder",
    "function recoveryReminderKeyOf",
    "function recoveryReminderPreparedIndex",
    "recoveryReminderStatus",
    "recovery_reminder_sent",
    "remindedSource",
    "kpiRecoveryReminders",
    "recoveryReminderStatusLedger",
    "recoveryReminderRevenueEur:0",
    "source KPI recovery reminder ledger row is not revenue",
    "Top recovery reminder attempt saved in qpvRecoveryReminderLedger. Revenue remains 0 EUR until verified paid.",
    "Top recovery buyer already has a source KPI reminder attempt. Duplicate blocked.",
    "No unpaid recovery buyer to mark reminded.",
    "markReminderConvertedHandoff",
    "function markReminderConvertedHandoff",
    "function conversionHandoffKeyOf",
    "function conversionHandoffPreparedIndex",
    "conversionHandoffStatus",
    "needs_manual_paid_verification",
    "handoffSource",
    "kpiConversionHandoffs",
    "recoveryConversionHandoffLedger",
    "Converted after reminder handoff ledger",
    "convertedAfterReminderRevenueEur:0",
    "converted after reminder handoff is not revenue",
    "No reminded unpaid buyer available for paid verification handoff, or duplicate handoff blocked.",
    "Converted-after-reminder handoff saved. Open manual paid gate; revenue remains 0 EUR until verified paid.",
    "kpiRecoverable",
    "kpiOverdue",
    "kpiStale",
    "kpiRecoveryRevenue",
    "function recoveryHref",
    "function recoveryRows",
    "recoveryQueueRevenueEur:0",
    "paymentRecoveryDashboard",
    "paymentRecoveryRule",
    "Source KPI admin exposes order-admin.html, revenue-command-center.html, payment-recovery-queue.html and paid-confirmation.html",
    "Only paid/delivered order rows count confirmed EUR",
    "proofSubmittedRevenueEur:0",
    "unverifiedProofRevenueEur:0",
    "followUpMessageRevenueEur:0",
    "preparedFollowUpRevenueEur:0",
    "priorityBucketRevenueEur:0",
    "proof_submitted_manual_review is not paid",
    "paymentReference text is not revenue",
    "source visit is not revenue",
    "lead event is not revenue",
    "checkout order is not revenue until paid",
    "generated follow-up message is not revenue",
    "prepared follow-up ledger row is not revenue",
    "priority aging bucket row is not revenue",
    "kpiSources",
    "kpiLeads",
    "kpiOrders",
    "kpiProofs",
    "kpiPaid",
    "kpiRevenue",
    "confirmedRevenueEur",
    "uniqueLeads",
    "paidRows",
    "copyUnpaidProofs",
    "downloadUnpaidProofs",
    "unpaidProofRows",
    "toUnpaidProofCsv",
    "qpv-unpaid-proof-follow-up.csv",
    "needs_manual_payment_follow_up",
    "copyFollowUps",
    "downloadFollowUps",
    "followUpMessage(row)",
    "toFollowUpMessages",
    "qpv-unpaid-proof-follow-up-messages.txt",
    "One-click buyer follow-up messages",
    "Generate one copy-ready buyer follow-up message per deduped unpaid proof row; paid and already prepared rows are excluded, with priority bucket included.",
    "Paid rows are excluded",
    "markFollowUps",
    "markFollowUpsPrepared",
    "followUpKeyOf",
    "followUpPreparedIndex",
    "followUpStatusLedger",
    "follow_up_prepared",
    "preparedSource",
    "source_kpi_admin",
    "already prepared rows are excluded",
    "Prepared follow-up rows are outreach state only; they suppress duplicate chasing and never count as revenue.",
    "Unpaid proof priority aging buckets",
    "priorityAgingBuckets",
    "function proofAgeDays",
    "function priorityBucket",
    "function priorityRank",
    "priorityAgingView",
    "hot_now_under_24h",
    "due_today_1d_plus",
    "overdue_3d_plus",
    "stale_rescue_7d_plus",
    "Priority aging bucket rows rank unpaid proof follow-up work only and never count as revenue.",
    "proofAgeDays",
    "priorityBucket",
    "priorityRank",
]

for marker in required:
    if marker not in html:
        raise SystemExit(f"FAIL: source KPI admin missing marker: {marker}")

for forbidden in [
    "proofSubmittedRevenueEur:19",
    "unverifiedProofRevenueEur:19",
    "followUpMessageRevenueEur:19",
    "preparedFollowUpRevenueEur:19",
    "priorityBucketRevenueEur:19",
    "recoveryQueueRevenueEur:19",
    "topRecoveryMessageRevenueEur:19",
    "recoveryReminderRevenueEur:19",
    "convertedAfterReminderRevenueEur:19",
]:
    if forbidden in html.replace(" ", ""):
        raise SystemExit(f"FAIL: source KPI admin accepts weak revenue pattern: {forbidden}")

print("PASS: source KPI admin filters source-attributed QPV ledgers, exports unpaid proofs, prioritizes unpaid proof aging buckets, generates deduped buyer follow-up messages, tracks prepared follow-up status in qpvFollowUpLedger, exposes payment-recovery-queue.html with recoverable unpaid counters/highest-priority buyer links, copies the top unpaid recovery message, records qpvRecoveryReminderLedger reminder attempts with duplicate suppression, creates qpvRecoveryConversionHandoffLedger handoffs to paid-confirmation.html for reminded buyers, and keeps unverified proof/source/follow-up/priority/recovery/reminder/handoff activity at 0 EUR.")
